- name: Erpnext
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'erpnext_selection'
      prompt: "\nPlease choose the number for ERPNext version [ 1/2/3 ] \n\n
      1: ERPNext11\n
      2: ERPNext12\n
      3: ERPNext13\n"
      private: no
      default: 2
  
  vars:
    erpnext_select:
      '1': '11'
      '2': '12'
      '3': '13'

    erpnext_version: "{{erpnext_select[erpnext_selection]}}" 
  
  roles:
    - {role: role_common , tags: "role_common"}
    - {role: role_cloud , tags: "role_cloud"}
    - {role: role_docker , tags: "role_docker"}
    - {role: role_mariadb , tags: "role_mariadb"}
    - {role: role_nginx , tags: "role_nginx"}
    - {role: erpnext , tags: "erpnext"}
    - {role: role_init , tags: "role_init"}
    - {role: role_preend , tags: "role_preend"}
    - {role: role_end , tags: "role_end"}